spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_select?useSSL=false
    username: root
    password: 123
  jpa:
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    hibernate:
      ddl-auto: validate
    show-sql: true
